// Code generated by me. DO NOT EDIT.

package goIdlCorba

import  "github.com/bhbosman/orb/src/omg"
import __fmt__ "fmt"
import __json__ "encoding/json"
import __omg__ "github.com/bhbosman/orb/src/omg"
import __reflect__ "reflect"
import __yaccidl__ "github.com/bhbosman/yaccidl"

// Enum declaration: "CORBA::TCKind", generatedBy by: "WriteEnumDcl"
type CorbaTCKind uint32

//noinspection GoUnusedConst
const (
	CorbaTCKindTkNull              CorbaTCKind = 0
	CorbaTCKindTkVoid              CorbaTCKind = 1
	CorbaTCKindTkShort             CorbaTCKind = 2
	CorbaTCKindTkLong              CorbaTCKind = 3
	CorbaTCKindTkUshort            CorbaTCKind = 4
	CorbaTCKindTkUlong             CorbaTCKind = 5
	CorbaTCKindTkFloat             CorbaTCKind = 6
	CorbaTCKindTkDouble            CorbaTCKind = 7
	CorbaTCKindTkBoolean           CorbaTCKind = 8
	CorbaTCKindTkChar              CorbaTCKind = 9
	CorbaTCKindTkOctet             CorbaTCKind = 10
	CorbaTCKindTkAny               CorbaTCKind = 11
	CorbaTCKindTkTypeCode          CorbaTCKind = 12
	CorbaTCKindTkPrincipal         CorbaTCKind = 13
	CorbaTCKindTkObjref            CorbaTCKind = 14
	CorbaTCKindTkStruct            CorbaTCKind = 15
	CorbaTCKindTkUnion             CorbaTCKind = 16
	CorbaTCKindTkEnum              CorbaTCKind = 17
	CorbaTCKindTkString            CorbaTCKind = 18
	CorbaTCKindTkSequence          CorbaTCKind = 19
	CorbaTCKindTkArray             CorbaTCKind = 20
	CorbaTCKindTkAlias             CorbaTCKind = 21
	CorbaTCKindTkExcept            CorbaTCKind = 22
	CorbaTCKindTkLonglong          CorbaTCKind = 23
	CorbaTCKindTkUlonglong         CorbaTCKind = 24
	CorbaTCKindTkLongdouble        CorbaTCKind = 25
	CorbaTCKindTkWchar             CorbaTCKind = 26
	CorbaTCKindTkWstring           CorbaTCKind = 27
	CorbaTCKindTkFixed             CorbaTCKind = 28
	CorbaTCKindTkValue             CorbaTCKind = 29
	CorbaTCKindTkValueBox          CorbaTCKind = 30
	CorbaTCKindTkNative            CorbaTCKind = 31
	CorbaTCKindTkAbstractInterface CorbaTCKind = 32
	CorbaTCKindTkLocalInterface    CorbaTCKind = 33
	CorbaTCKindTkComponent         CorbaTCKind = 34
	CorbaTCKindTkHome              CorbaTCKind = 35
	CorbaTCKindTkEvent             CorbaTCKind = 36
)

//noinspection GoSnakeCaseUsage
type CorbaTCKind_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CorbaTCKindId_Const = "IDL:omg.org/CORBA/TCKind:1.0"

func (self CorbaTCKind_Helper) Id() string {
	return CorbaTCKindId_Const
}

func (self CorbaTCKind_Helper) Read(stream IReadAny) (uint32, error) {
	result, err := IdlUInt32Helper.Read(stream)
	return result, err
}

func (self CorbaTCKind_Helper) Write(stream IWriteAny, v uint32) error {
	return IdlUInt32Helper.Write(stream, v)
}

// TypeDef declaration: "CORBA::ValueModifier", generatedBy by: "WriteTypeDefOfPrimitiveDcl"
//Typedef Primitive declaration: "CORBA::ValueModifier" from: "int16"
type CorbaValueModifier int16

//noinspection GoSnakeCaseUsage
type CorbaValueModifier_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CorbaValueModifierId_Const = "IDL:omg.org/CORBA/ValueModifier:1.0"

func (self CorbaValueModifier_Helper) Id() string {
	return CorbaValueModifierId_Const
}

func (self CorbaValueModifier_Helper) Read(stream IReadAny) (int16, error) {
	result, err := IdlShortHelper.Read(stream)
	return result, err
}

func (self CorbaValueModifier_Helper) Write(stream IWriteAny, v int16) error {
	return IdlShortHelper.Write(stream, v)
}

// Constant declaration: "CORBA::VM_NONE", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CorbaVmNone int16 = 0

// Constant declaration: "CORBA::VM_CUSTOM", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CorbaVmCustom int16 = 1

// Constant declaration: "CORBA::VM_ABSTRACT", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CorbaVmAbstract int16 = 2

// Constant declaration: "CORBA::VM_TRUNCATABLE", generatedBy by: "WriteConstantValue"
//noinspection GoUnusedConst
const CorbaVmTruncatable int16 = 3

// Exception declaration: "CORBA::TypeCode::Bounds", generatedBy by: "WriteStructDcl"
// Exception Decl: true
type CorbaTypeCodeBounds struct {
	IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaTypeCodeBoundsId_Const = "IDL:omg.org/CORBA/TypeCode/Bounds:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultCorbaTypeCodeBounds() *CorbaTypeCodeBounds {
	//noinspection GoRedundantConversion
	return &CorbaTypeCodeBounds{
		IdlObject: IdlObject{
			Id: CorbaTypeCodeBoundsId_Const,
		},
	}
}

//noinspection GoUnusedExportedFunction
func NewCorbaTypeCodeBounds() *CorbaTypeCodeBounds {
	//noinspection GoRedundantConversion
	return &CorbaTypeCodeBounds{
		IdlObject: IdlObject{
			Id: CorbaTypeCodeBoundsId_Const,
		},
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomCorbaTypeCodeBounds() *CorbaTypeCodeBounds {
	//noinspection GoRedundantConversion
	return &CorbaTypeCodeBounds{
		IdlObject: IdlObject{
			Id: CorbaTypeCodeBoundsId_Const,
		},
	}
}

func (self *CorbaTypeCodeBounds) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaTypeCodeBounds) Error() string{
	return 	__fmt__.Sprintf("Error of type CorbaTypeCodeBounds(%v)", self.String())
}
func (self *CorbaTypeCodeBounds) GoString() string {
	return self.String()
}

func (self *CorbaTypeCodeBounds) ReadValue(stream IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaTypeCodeBounds) Read(stream IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaTypeCodeBounds) Write(stream IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaTypeCodeBounds_Helper struct {
}

//noinspection GoSnakeCaseUsage
func (self *CorbaTypeCodeBounds_Helper) CreateTypeCode(orb CorbaOrb) (CorbaTypeCode, error) {
	var err error
	var memberSeq CorbaStructMemberSeq = nil
	err = self.AddMembers(orb, &memberSeq)
	if err != nil {
		return nil, err
	}
	return nil, nil
}

//noinspection GoSnakeCaseUsage
func (self *CorbaTypeCodeBounds_Helper) AddMembers(orb CorbaOrb, memberSeq *CorbaStructMemberSeq) error {
	err := IdlObjectHelper.AddMembers(orb, memberSeq)
	if err != nil {
		return err
	}
	return nil
}

// Exception declaration: "CORBA::TypeCode::BadKind", generatedBy by: "WriteStructDcl"
// Exception Decl: true
type CorbaTypeCodeBadKind struct {
	IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaTypeCodeBadKindId_Const = "IDL:omg.org/CORBA/TypeCode/BadKind:1.0"

//noinspection GoUnusedExportedFunction
func NewDefaultCorbaTypeCodeBadKind() *CorbaTypeCodeBadKind {
	//noinspection GoRedundantConversion
	return &CorbaTypeCodeBadKind{
		IdlObject: IdlObject{
			Id: CorbaTypeCodeBadKindId_Const,
		},
	}
}

//noinspection GoUnusedExportedFunction
func NewCorbaTypeCodeBadKind() *CorbaTypeCodeBadKind {
	//noinspection GoRedundantConversion
	return &CorbaTypeCodeBadKind{
		IdlObject: IdlObject{
			Id: CorbaTypeCodeBadKindId_Const,
		},
	}
}

//noinspection GoUnusedExportedFunction
func NewRandomCorbaTypeCodeBadKind() *CorbaTypeCodeBadKind {
	//noinspection GoRedundantConversion
	return &CorbaTypeCodeBadKind{
		IdlObject: IdlObject{
			Id: CorbaTypeCodeBadKindId_Const,
		},
	}
}

func (self *CorbaTypeCodeBadKind) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaTypeCodeBadKind) Error() string{
	return 	__fmt__.Sprintf("Error of type CorbaTypeCodeBadKind(%v)", self.String())
}
func (self *CorbaTypeCodeBadKind) GoString() string {
	return self.String()
}

func (self *CorbaTypeCodeBadKind) ReadValue(stream IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaTypeCodeBadKind) Read(stream IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaTypeCodeBadKind) Write(stream IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaTypeCodeBadKind_Helper struct {
}

//noinspection GoSnakeCaseUsage
func (self *CorbaTypeCodeBadKind_Helper) CreateTypeCode(orb CorbaOrb) (CorbaTypeCode, error) {
	var err error
	var memberSeq CorbaStructMemberSeq = nil
	err = self.AddMembers(orb, &memberSeq)
	if err != nil {
		return nil, err
	}
	return nil, nil
}

//noinspection GoSnakeCaseUsage
func (self *CorbaTypeCodeBadKind_Helper) AddMembers(orb CorbaOrb, memberSeq *CorbaStructMemberSeq) error {
	err := IdlObjectHelper.AddMembers(orb, memberSeq)
	if err != nil {
		return err
	}
	return nil
}

// Interface declaration: "CORBA::TypeCode", generatedBy by: "WriteInterface"
type CorbaTypeCode interface {
	// Interface operations
	// Original name: "equal"
	Equal(Tc CorbaTypeCode) (result bool, err error)
	// Original name: "equivalent"
	Equivalent(Tc CorbaTypeCode) (result bool, err error)
	// Original name: "get_compact_typecode"
	GetCompactTypecode() (result CorbaTypeCode, err error)
	// Original name: "kind"
	Kind() (result uint32, err error)
	//Exceptions for : Id
	//	CorbaTypeCodeBadKind
	// Original name: "id"
	Id() (result CorbaRepositoryId, err error)
	//Exceptions for : Name
	//	CorbaTypeCodeBadKind
	// Original name: "name"
	Name() (result CorbaIdentifier, err error)
	//Exceptions for : MemberCount
	//	CorbaTypeCodeBadKind
	// Original name: "member_count"
	MemberCount() (result uint32, err error)
	//Exceptions for : MemberName
	//	CorbaTypeCodeBadKind
	//	CorbaTypeCodeBounds
	// Original name: "member_name"
	MemberName(Index uint32) (result CorbaIdentifier, err error)
	//Exceptions for : MemberType
	//	CorbaTypeCodeBadKind
	//	CorbaTypeCodeBounds
	// Original name: "member_type"
	MemberType(Index uint32) (result CorbaTypeCode, err error)
	//Exceptions for : MemberLabel
	//	CorbaTypeCodeBadKind
	//	CorbaTypeCodeBounds
	// Original name: "member_label"
	MemberLabel(Index uint32) (result IdlAny, err error)
	//Exceptions for : DiscriminatorType
	//	CorbaTypeCodeBadKind
	// Original name: "discriminator_type"
	DiscriminatorType() (result CorbaTypeCode, err error)
	//Exceptions for : DefaultIndex
	//	CorbaTypeCodeBadKind
	// Original name: "default_index"
	DefaultIndex() (result int32, err error)
	//Exceptions for : Length
	//	CorbaTypeCodeBadKind
	// Original name: "length"
	Length() (result uint32, err error)
	//Exceptions for : ContentType
	//	CorbaTypeCodeBadKind
	// Original name: "content_type"
	ContentType() (result CorbaTypeCode, err error)
	//Exceptions for : FixedDigits
	//	CorbaTypeCodeBadKind
	// Original name: "fixed_digits"
	FixedDigits() (result uint16, err error)
	//Exceptions for : FixedScale
	//	CorbaTypeCodeBadKind
	// Original name: "fixed_scale"
	FixedScale() (result int16, err error)
	//Exceptions for : MemberVisibility
	//	CorbaTypeCodeBadKind
	//	CorbaTypeCodeBounds
	// Original name: "member_visibility"
	MemberVisibility(Index uint32) (result int16, err error)
	//Exceptions for : TypeModifier
	//	CorbaTypeCodeBadKind
	// Original name: "type_modifier"
	TypeModifier() (result int16, err error)
	//Exceptions for : ConcreteBaseType
	//	CorbaTypeCodeBadKind
	// Original name: "concrete_base_type"
	ConcreteBaseType() (result CorbaTypeCode, err error)
}

//noinspection GoSnakeCaseUsage
type CorbaTypeCode_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CorbaTypeCodeId_Const = "IDL:omg.org/CORBA/TypeCode:1.0"

func (self CorbaTypeCode_Helper) Id() string {
	return CorbaTypeCodeId_Const
}

func (self CorbaTypeCode_Helper) Read(stream IReadAny) (CorbaTypeCode, error) {
	return nil, nil
}

func (self CorbaTypeCode_Helper) Write(stream IWriteAny, v CorbaTypeCode) error {
	return nil
}


//noinspection GoUnusedGlobalVariable
var CorbaTCKindHelper = CorbaTCKind_Helper{}

//noinspection GoUnusedGlobalVariable
var CorbaValueModifierHelper = CorbaValueModifier_Helper{}

//noinspection GoUnusedGlobalVariable
var CorbaTypeCodeBoundsHelper = CorbaTypeCodeBounds_Helper{}

//noinspection GoUnusedGlobalVariable
var CorbaTypeCodeBadKindHelper = CorbaTypeCodeBadKind_Helper{}

//noinspection GoUnusedGlobalVariable
var CorbaTypeCodeHelper = CorbaTypeCode_Helper{}

func init() {
	AddRegistration(
		NewRegistrationInformation(
			CorbaTypeCodeBoundsId_Const,
			__yaccidl__.IdlStruct,
			"CORBA_TypeCode.idl.go",
			func() IIdlObject {
				return NewDefaultCorbaTypeCodeBounds()
			},
			func(generator IRandomDataGenerator) IIdlObject {
				return NewDefaultCorbaTypeCodeBounds()
			},
			 __reflect__.TypeOf((*CorbaTypeCodeBounds)(nil))))
	AddRegistration(
		NewRegistrationInformation(
			CorbaTypeCodeBadKindId_Const,
			__yaccidl__.IdlStruct,
			"CORBA_TypeCode.idl.go",
			func() IIdlObject {
				return NewDefaultCorbaTypeCodeBadKind()
			},
			func(generator IRandomDataGenerator) IIdlObject {
				return NewDefaultCorbaTypeCodeBadKind()
			},
			 __reflect__.TypeOf((*CorbaTypeCodeBadKind)(nil))))
}
