// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::ContainedSeq", generatedBy by: "WriteStructSequenceDcl"
type CorbaContainedSeq struct {
	__goidl__.IdlObject
	Array []CorbaContained `json:"Array"`
}

//noinspection GoSnakeCaseUsage
const CorbaContainedSeqId_Const = "IDL:CORBA/ContainedSeq:1.0"

func (self *CorbaContainedSeq) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaContainedSeq) GoString() string {
	return self.String()
}

func (self *CorbaContainedSeq) ReadValue(stream __goidl__.IReadAny) error {
	return nil
}

func (self *CorbaContainedSeq) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaContainedSeq) Write(stream __goidl__.IWriteAny) error {
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaContainedSeq_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaContainedSeqHelper = CorbaContainedSeq_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaContainedSeqId_Const,
			__goidl__.SequenceType,
			"CORBA_InterfaceRepository.idl",
			"xdl_CorbaContainedSeq.go",
			func() __goidl__.IIdlObject {
				return &CorbaContainedSeq{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaContainedSeq{}
			},
			__reflect__.TypeOf((*CorbaContainedSeq)(nil))))
}
