// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::ExtValueDef_describe_value_In", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaExtValueDefDescribeValueIn struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaExtValueDefDescribeValueInId_Const = "IDL:CORBA/ExtValueDef_describe_value_In:1.0"

func (self *CorbaExtValueDefDescribeValueIn) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaExtValueDefDescribeValueIn) GoString() string {
	return self.String()
}

func (self *CorbaExtValueDefDescribeValueIn) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaExtValueDefDescribeValueIn) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaExtValueDefDescribeValueIn) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaExtValueDefDescribeValueIn_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaExtValueDefDescribeValueInHelper = CorbaExtValueDefDescribeValueIn_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaExtValueDefDescribeValueInId_Const,
			__goidl__.StructType,
			"CORBA_InterfaceRepository.idl",
			"xdl_CorbaExtValueDefDescribeValueIn.go",
			func() __goidl__.IIdlObject {
				return &CorbaExtValueDefDescribeValueIn{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaExtValueDefDescribeValueIn{}
			},
			__reflect__.TypeOf((*CorbaExtValueDefDescribeValueIn)(nil))))
}
