// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::PollableSet_remove_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaPollableSetRemoveOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaPollableSetRemoveOutId_Const = "IDL:CORBA/PollableSet_remove_Out:1.0"

func (self *CorbaPollableSetRemoveOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaPollableSetRemoveOut) GoString() string {
	return self.String()
}

func (self *CorbaPollableSetRemoveOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaPollableSetRemoveOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaPollableSetRemoveOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaPollableSetRemoveOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaPollableSetRemoveOutHelper = CorbaPollableSetRemoveOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaPollableSetRemoveOutId_Const,
			__goidl__.StructType,
			"CORBA_Pollable.idl",
			"xdl_CorbaPollableSetRemoveOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaPollableSetRemoveOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaPollableSetRemoveOut{}
			},
			__reflect__.TypeOf((*CorbaPollableSetRemoveOut)(nil))))
}
