// Code generated by me. DO NOT EDIT.

package goIdlCorba

// Struct declaration: "CORBA::InterfaceAttrExtension_Stub", generatedBy by: "WriteStructDcl"
type CorbaInterfaceAttrExtensionStub struct {
}


func init() {
}
