// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"

// Enum declaration: "CORBA::DefinitionKind", generatedBy by: "WriteEnumDcl"
type CorbaDefinitionKind uint32

//noinspection GoUnusedConst
const (
	CorbaDefinitionKindDkNone              CorbaDefinitionKind = 0
	CorbaDefinitionKindDkAll               CorbaDefinitionKind = 1
	CorbaDefinitionKindDkAttribute         CorbaDefinitionKind = 2
	CorbaDefinitionKindDkConstant          CorbaDefinitionKind = 3
	CorbaDefinitionKindDkException         CorbaDefinitionKind = 4
	CorbaDefinitionKindDkInterface         CorbaDefinitionKind = 5
	CorbaDefinitionKindDkModule            CorbaDefinitionKind = 6
	CorbaDefinitionKindDkOperation         CorbaDefinitionKind = 7
	CorbaDefinitionKindDkTypedef           CorbaDefinitionKind = 8
	CorbaDefinitionKindDkAlias             CorbaDefinitionKind = 9
	CorbaDefinitionKindDkStruct            CorbaDefinitionKind = 10
	CorbaDefinitionKindDkUnion             CorbaDefinitionKind = 11
	CorbaDefinitionKindDkEnum              CorbaDefinitionKind = 12
	CorbaDefinitionKindDkPrimitive         CorbaDefinitionKind = 13
	CorbaDefinitionKindDkString            CorbaDefinitionKind = 14
	CorbaDefinitionKindDkSequence          CorbaDefinitionKind = 15
	CorbaDefinitionKindDkArray             CorbaDefinitionKind = 16
	CorbaDefinitionKindDkRepository        CorbaDefinitionKind = 17
	CorbaDefinitionKindDkWstring           CorbaDefinitionKind = 18
	CorbaDefinitionKindDkFixed             CorbaDefinitionKind = 19
	CorbaDefinitionKindDkValue             CorbaDefinitionKind = 20
	CorbaDefinitionKindDkValueBox          CorbaDefinitionKind = 21
	CorbaDefinitionKindDkValueMember       CorbaDefinitionKind = 22
	CorbaDefinitionKindDkNative            CorbaDefinitionKind = 23
	CorbaDefinitionKindDkAbstractInterface CorbaDefinitionKind = 24
	CorbaDefinitionKindDkLocalInterface    CorbaDefinitionKind = 25
	CorbaDefinitionKindDkComponent         CorbaDefinitionKind = 26
	CorbaDefinitionKindDkHome              CorbaDefinitionKind = 27
	CorbaDefinitionKindDkFactory           CorbaDefinitionKind = 28
	CorbaDefinitionKindDkFinder            CorbaDefinitionKind = 29
	CorbaDefinitionKindDkEmits             CorbaDefinitionKind = 30
	CorbaDefinitionKindDkPublishes         CorbaDefinitionKind = 31
	CorbaDefinitionKindDkConsumes          CorbaDefinitionKind = 32
	CorbaDefinitionKindDkProvides          CorbaDefinitionKind = 33
	CorbaDefinitionKindDkUses              CorbaDefinitionKind = 34
	CorbaDefinitionKindDkEvent             CorbaDefinitionKind = 35
)

//noinspection GoSnakeCaseUsage
type CorbaDefinitionKind_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CorbaDefinitionKindId_Const = "IDL:omg.org/CORBA/DefinitionKind:1.0"

func (self CorbaDefinitionKind_Helper) Id() string {
	return CorbaDefinitionKindId_Const
}

func (self CorbaDefinitionKind_Helper) Read(stream __goidl__.IReadAny) (uint32, error) {
	result, err := __goidl__.IdlUInt32Helper.Read(stream)
	return result, err
}

func (self CorbaDefinitionKind_Helper) Write(stream __goidl__.IWriteAny, v uint32) error {
	return __goidl__.IdlUInt32Helper.Write(stream, v)
}


//noinspection GoUnusedGlobalVariable
var CorbaDefinitionKindHelper = CorbaDefinitionKind_Helper{}

func init() {
}
