// Code generated by me. DO NOT EDIT.

package goIdlCorba

// Struct declaration: "CORBA::ExtAttributeDef_Stub", generatedBy by: "WriteStructDcl"
type CorbaExtAttributeDefStub struct {
}


func init() {
}
