// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::Request_sendp_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaRequestSendpOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaRequestSendpOutId_Const = "IDL:CORBA/Request_sendp_Out:1.0"

func (self *CorbaRequestSendpOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaRequestSendpOut) GoString() string {
	return self.String()
}

func (self *CorbaRequestSendpOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaRequestSendpOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaRequestSendpOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaRequestSendpOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaRequestSendpOutHelper = CorbaRequestSendpOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaRequestSendpOutId_Const,
			__goidl__.StructType,
			"CORBA_Request.idl",
			"xdl_CorbaRequestSendpOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaRequestSendpOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaRequestSendpOut{}
			},
			__reflect__.TypeOf((*CorbaRequestSendpOut)(nil))))
}
