// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::ComponentIR::EventDef_describe_ext_value_In", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaComponentIREventDefDescribeExtValueIn struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaComponentIREventDefDescribeExtValueInId_Const = "IDL:CORBA/ComponentIR/EventDef_describe_ext_value_In:1.0"

func (self *CorbaComponentIREventDefDescribeExtValueIn) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaComponentIREventDefDescribeExtValueIn) GoString() string {
	return self.String()
}

func (self *CorbaComponentIREventDefDescribeExtValueIn) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaComponentIREventDefDescribeExtValueIn) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaComponentIREventDefDescribeExtValueIn) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaComponentIREventDefDescribeExtValueIn_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaComponentIREventDefDescribeExtValueInHelper = CorbaComponentIREventDefDescribeExtValueIn_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaComponentIREventDefDescribeExtValueInId_Const,
			__goidl__.StructType,
			"CORBA_InterfaceRepository.idl",
			"xdl_CorbaComponentIREventDefDescribeExtValueIn.go",
			func() __goidl__.IIdlObject {
				return &CorbaComponentIREventDefDescribeExtValueIn{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaComponentIREventDefDescribeExtValueIn{}
			},
			__reflect__.TypeOf((*CorbaComponentIREventDefDescribeExtValueIn)(nil))))
}
