// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"

// Interface declaration: "CORBA::ComponentIR::Container", generatedBy by: "WriteInterface"
type CorbaComponentIRContainer interface {
	// Original name: "create_component"
	CreateComponent(params CorbaComponentIRContainerCreateComponentIn) (CorbaComponentIRContainerCreateComponentOut, error)
	// Original name: "create_event"
	CreateEvent(params CorbaComponentIRContainerCreateEventIn) (CorbaComponentIRContainerCreateEventOut, error)
	// Original name: "create_home"
	CreateHome(params CorbaComponentIRContainerCreateHomeIn) (CorbaComponentIRContainerCreateHomeOut, error)
}

const CorbaComponentIRContainerCreateComponentOperation = "create_component"
const CorbaComponentIRContainerCreateEventOperation = "create_event"
const CorbaComponentIRContainerCreateHomeOperation = "create_home"
//noinspection GoSnakeCaseUsage
type CorbaComponentIRContainer_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CorbaComponentIRContainerId_Const = "IDL:omg.org/CORBA/ComponentIR/Container:1.0"

func (self CorbaComponentIRContainer_Helper) Id() string {
	return CorbaComponentIRContainerId_Const
}

func (self CorbaComponentIRContainer_Helper) Read(stream __goidl__.IReadAny) (CorbaComponentIRContainer, error) {
	return nil, nil
}

func (self CorbaComponentIRContainer_Helper) Write(stream __goidl__.IWriteAny, v CorbaComponentIRContainer) error {
	return nil
}


//noinspection GoUnusedGlobalVariable
var CorbaComponentIRContainerHelper = CorbaComponentIRContainer_Helper{}

func init() {
}
