// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"

// Interface declaration: "CORBA::ComponentIR::EmitsDef", generatedBy by: "WriteInterface"
type CorbaComponentIREmitsDef interface {
	// Original name: "is_a"
	IsA(params CorbaComponentIREmitsDefIsAIn) (CorbaComponentIREmitsDefIsAOut, error)
}

const CorbaComponentIREmitsDefIsAOperation = "is_a"
//noinspection GoSnakeCaseUsage
type CorbaComponentIREmitsDef_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CorbaComponentIREmitsDefId_Const = "IDL:omg.org/CORBA/ComponentIR/EmitsDef:1.0"

func (self CorbaComponentIREmitsDef_Helper) Id() string {
	return CorbaComponentIREmitsDefId_Const
}

func (self CorbaComponentIREmitsDef_Helper) Read(stream __goidl__.IReadAny) (CorbaComponentIREmitsDef, error) {
	return nil, nil
}

func (self CorbaComponentIREmitsDef_Helper) Write(stream __goidl__.IWriteAny, v CorbaComponentIREmitsDef) error {
	return nil
}


//noinspection GoUnusedGlobalVariable
var CorbaComponentIREmitsDefHelper = CorbaComponentIREmitsDef_Helper{}

func init() {
}
