// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::ExtValueDef_is_a_In", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaExtValueDefIsAIn struct {
	__goidl__.IdlObject
	Id string `json:"Id"`
}

//noinspection GoSnakeCaseUsage
const CorbaExtValueDefIsAInId_Const = "IDL:CORBA/ExtValueDef_is_a_In:1.0"

func (self *CorbaExtValueDefIsAIn) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaExtValueDefIsAIn) GoString() string {
	return self.String()
}

func (self *CorbaExtValueDefIsAIn) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(StringType)
	self.Id, err = __goidl__.IdlStringHelper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaExtValueDefIsAIn) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaExtValueDefIsAIn) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(StringType)
	err = __goidl__.IdlStringHelper.Write(stream, self.Id)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaExtValueDefIsAIn_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaExtValueDefIsAInHelper = CorbaExtValueDefIsAIn_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaExtValueDefIsAInId_Const,
			__goidl__.StructType,
			"CORBA_InterfaceRepository.idl",
			"xdl_CorbaExtValueDefIsAIn.go",
			func() __goidl__.IIdlObject {
				return &CorbaExtValueDefIsAIn{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaExtValueDefIsAIn{}
			},
			__reflect__.TypeOf((*CorbaExtValueDefIsAIn)(nil))))
}
