// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::ComponentIR::ConsumesDef_is_a_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaComponentIRConsumesDefIsAOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaComponentIRConsumesDefIsAOutId_Const = "IDL:CORBA/ComponentIR/ConsumesDef_is_a_Out:1.0"

func (self *CorbaComponentIRConsumesDefIsAOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaComponentIRConsumesDefIsAOut) GoString() string {
	return self.String()
}

func (self *CorbaComponentIRConsumesDefIsAOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaComponentIRConsumesDefIsAOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaComponentIRConsumesDefIsAOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaComponentIRConsumesDefIsAOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaComponentIRConsumesDefIsAOutHelper = CorbaComponentIRConsumesDefIsAOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaComponentIRConsumesDefIsAOutId_Const,
			__goidl__.StructType,
			"CORBA_InterfaceRepository.idl",
			"xdl_CorbaComponentIRConsumesDefIsAOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaComponentIRConsumesDefIsAOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaComponentIRConsumesDefIsAOut{}
			},
			__reflect__.TypeOf((*CorbaComponentIRConsumesDefIsAOut)(nil))))
}
