// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __fmt__ "fmt"
import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Exception declaration: "CORBA::BadFixedValue", generatedBy by: "WriteStructDcl"
// Exception Decl: true
type CorbaBadFixedValue struct {
	__goidl__.IdlObject
	Offset uint32 `json:"Offset"`
}

//noinspection GoSnakeCaseUsage
const CorbaBadFixedValueId_Const = "IDL:omg.org/CORBA/BadFixedValue:1.0"

func (self *CorbaBadFixedValue) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaBadFixedValue) Error() string{
	return 	__fmt__.Sprintf("Error of type CorbaBadFixedValue(%v)", self.String())
}
func (self *CorbaBadFixedValue) GoString() string {
	return self.String()
}

func (self *CorbaBadFixedValue) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(UnsignedLongType)
	self.Offset, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaBadFixedValue) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaBadFixedValue) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(UnsignedLongType)
	err = __goidl__.IdlUInt32Helper.Write(stream, self.Offset)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaBadFixedValue_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaBadFixedValueHelper = CorbaBadFixedValue_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaBadFixedValueId_Const,
			__goidl__.StructType,
			"CORBA_Stream.idl",
			"xdl_CorbaBadFixedValue.go",
			func() __goidl__.IIdlObject {
				return &CorbaBadFixedValue{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaBadFixedValue{}
			},
			__reflect__.TypeOf((*CorbaBadFixedValue)(nil))))
}
