// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::CustomMarshal_unmarshal_In", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaCustomMarshalUnmarshalIn struct {
	__goidl__.IdlObject
	Is CorbaDataInputStream `json:"Is"`
}

//noinspection GoSnakeCaseUsage
const CorbaCustomMarshalUnmarshalInId_Const = "IDL:CORBA/CustomMarshal_unmarshal_In:1.0"

func (self *CorbaCustomMarshalUnmarshalIn) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaCustomMarshalUnmarshalIn) GoString() string {
	return self.String()
}

func (self *CorbaCustomMarshalUnmarshalIn) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlInterface)
	self.Is, err = CorbaDataInputStreamHelper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaCustomMarshalUnmarshalIn) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaCustomMarshalUnmarshalIn) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlInterface)
	err = CorbaDataInputStreamHelper.Write(stream, self.Is)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaCustomMarshalUnmarshalIn_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaCustomMarshalUnmarshalInHelper = CorbaCustomMarshalUnmarshalIn_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaCustomMarshalUnmarshalInId_Const,
			__goidl__.StructType,
			"CORBA_CustomMarshal.idl",
			"xdl_CorbaCustomMarshalUnmarshalIn.go",
			func() __goidl__.IIdlObject {
				return &CorbaCustomMarshalUnmarshalIn{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaCustomMarshalUnmarshalIn{}
			},
			__reflect__.TypeOf((*CorbaCustomMarshalUnmarshalIn)(nil))))
}
