// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::ExtAbstractInterfaceDefSeq", generatedBy by: "WriteStructSequenceDcl"
type CorbaExtAbstractInterfaceDefSeq struct {
	__goidl__.IdlObject
	Array []CorbaExtAbstractInterfaceDef `json:"Array"`
}

//noinspection GoSnakeCaseUsage
const CorbaExtAbstractInterfaceDefSeqId_Const = "IDL:CORBA/ExtAbstractInterfaceDefSeq:1.0"

func (self *CorbaExtAbstractInterfaceDefSeq) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaExtAbstractInterfaceDefSeq) GoString() string {
	return self.String()
}

func (self *CorbaExtAbstractInterfaceDefSeq) ReadValue(stream __goidl__.IReadAny) error {
	return nil
}

func (self *CorbaExtAbstractInterfaceDefSeq) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaExtAbstractInterfaceDefSeq) Write(stream __goidl__.IWriteAny) error {
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaExtAbstractInterfaceDefSeq_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaExtAbstractInterfaceDefSeqHelper = CorbaExtAbstractInterfaceDefSeq_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaExtAbstractInterfaceDefSeqId_Const,
			__goidl__.SequenceType,
			"CORBA_InterfaceRepository.idl",
			"xdl_CorbaExtAbstractInterfaceDefSeq.go",
			func() __goidl__.IIdlObject {
				return &CorbaExtAbstractInterfaceDefSeq{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaExtAbstractInterfaceDefSeq{}
			},
			__reflect__.TypeOf((*CorbaExtAbstractInterfaceDefSeq)(nil))))
}
