// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"

// Interface declaration: "CORBA::Container", generatedBy by: "WriteInterface"
type CorbaContainer interface {
	// Original name: "contents"
	Contents(params CorbaContainerContentsIn) (CorbaContainerContentsOut, error)
	// Original name: "create_abstract_interface"
	CreateAbstractInterface(params CorbaContainerCreateAbstractInterfaceIn) (CorbaContainerCreateAbstractInterfaceOut, error)
	// Original name: "create_alias"
	CreateAlias(params CorbaContainerCreateAliasIn) (CorbaContainerCreateAliasOut, error)
	// Original name: "create_constant"
	CreateConstant(params CorbaContainerCreateConstantIn) (CorbaContainerCreateConstantOut, error)
	// Original name: "create_enum"
	CreateEnum(params CorbaContainerCreateEnumIn) (CorbaContainerCreateEnumOut, error)
	// Original name: "create_exception"
	CreateException(params CorbaContainerCreateExceptionIn) (CorbaContainerCreateExceptionOut, error)
	// Original name: "create_ext_value"
	CreateExtValue(params CorbaContainerCreateExtValueIn) (CorbaContainerCreateExtValueOut, error)
	// Original name: "create_interface"
	CreateInterface(params CorbaContainerCreateInterfaceIn) (CorbaContainerCreateInterfaceOut, error)
	// Original name: "create_local_interface"
	CreateLocalInterface(params CorbaContainerCreateLocalInterfaceIn) (CorbaContainerCreateLocalInterfaceOut, error)
	// Original name: "create_module"
	CreateModule(params CorbaContainerCreateModuleIn) (CorbaContainerCreateModuleOut, error)
	// Original name: "create_native"
	CreateNative(params CorbaContainerCreateNativeIn) (CorbaContainerCreateNativeOut, error)
	// Original name: "create_struct"
	CreateStruct(params CorbaContainerCreateStructIn) (CorbaContainerCreateStructOut, error)
	// Original name: "create_union"
	CreateUnion(params CorbaContainerCreateUnionIn) (CorbaContainerCreateUnionOut, error)
	// Original name: "create_value"
	CreateValue(params CorbaContainerCreateValueIn) (CorbaContainerCreateValueOut, error)
	// Original name: "create_value_box"
	CreateValueBox(params CorbaContainerCreateValueBoxIn) (CorbaContainerCreateValueBoxOut, error)
	// Original name: "describe_contents"
	DescribeContents(params CorbaContainerDescribeContentsIn) (CorbaContainerDescribeContentsOut, error)
	// Original name: "destroy"
	Destroy(params CorbaContainerDestroyIn) (CorbaContainerDestroyOut, error)
	// Original name: "lookup"
	Lookup(params CorbaContainerLookupIn) (CorbaContainerLookupOut, error)
	// Original name: "lookup_name"
	LookupName(params CorbaContainerLookupNameIn) (CorbaContainerLookupNameOut, error)
}

const CorbaContainerContentsOperation = "contents"
const CorbaContainerCreateAbstractInterfaceOperation = "create_abstract_interface"
const CorbaContainerCreateAliasOperation = "create_alias"
const CorbaContainerCreateConstantOperation = "create_constant"
const CorbaContainerCreateEnumOperation = "create_enum"
const CorbaContainerCreateExceptionOperation = "create_exception"
const CorbaContainerCreateExtValueOperation = "create_ext_value"
const CorbaContainerCreateInterfaceOperation = "create_interface"
const CorbaContainerCreateLocalInterfaceOperation = "create_local_interface"
const CorbaContainerCreateModuleOperation = "create_module"
const CorbaContainerCreateNativeOperation = "create_native"
const CorbaContainerCreateStructOperation = "create_struct"
const CorbaContainerCreateUnionOperation = "create_union"
const CorbaContainerCreateValueOperation = "create_value"
const CorbaContainerCreateValueBoxOperation = "create_value_box"
const CorbaContainerDescribeContentsOperation = "describe_contents"
const CorbaContainerDestroyOperation = "destroy"
const CorbaContainerLookupOperation = "lookup"
const CorbaContainerLookupNameOperation = "lookup_name"
//noinspection GoSnakeCaseUsage
type CorbaContainer_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CorbaContainerId_Const = "IDL:omg.org/CORBA/Container:1.0"

func (self CorbaContainer_Helper) Id() string {
	return CorbaContainerId_Const
}

func (self CorbaContainer_Helper) Read(stream __goidl__.IReadAny) (CorbaContainer, error) {
	return nil, nil
}

func (self CorbaContainer_Helper) Write(stream __goidl__.IWriteAny, v CorbaContainer) error {
	return nil
}


//noinspection GoUnusedGlobalVariable
var CorbaContainerHelper = CorbaContainer_Helper{}

func init() {
}
