// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::ComponentIR::Repository_get_primitive_In", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaComponentIRRepositoryGetPrimitiveIn struct {
	__goidl__.IdlObject
	Kind uint32 `json:"Kind"`
}

//noinspection GoSnakeCaseUsage
const CorbaComponentIRRepositoryGetPrimitiveInId_Const = "IDL:CORBA/ComponentIR/Repository_get_primitive_In:1.0"

func (self *CorbaComponentIRRepositoryGetPrimitiveIn) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaComponentIRRepositoryGetPrimitiveIn) GoString() string {
	return self.String()
}

func (self *CorbaComponentIRRepositoryGetPrimitiveIn) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlEnum)
	self.Kind, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaComponentIRRepositoryGetPrimitiveIn) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaComponentIRRepositoryGetPrimitiveIn) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlEnum)
	err = __goidl__.IdlUInt32Helper.Write(stream, self.Kind)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaComponentIRRepositoryGetPrimitiveIn_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaComponentIRRepositoryGetPrimitiveInHelper = CorbaComponentIRRepositoryGetPrimitiveIn_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaComponentIRRepositoryGetPrimitiveInId_Const,
			__goidl__.StructType,
			"CORBA_InterfaceRepository.idl",
			"xdl_CorbaComponentIRRepositoryGetPrimitiveIn.go",
			func() __goidl__.IIdlObject {
				return &CorbaComponentIRRepositoryGetPrimitiveIn{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaComponentIRRepositoryGetPrimitiveIn{}
			},
			__reflect__.TypeOf((*CorbaComponentIRRepositoryGetPrimitiveIn)(nil))))
}
