// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::Request_get_response_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaRequestGetResponseOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaRequestGetResponseOutId_Const = "IDL:CORBA/Request_get_response_Out:1.0"

func (self *CorbaRequestGetResponseOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaRequestGetResponseOut) GoString() string {
	return self.String()
}

func (self *CorbaRequestGetResponseOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaRequestGetResponseOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaRequestGetResponseOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaRequestGetResponseOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaRequestGetResponseOutHelper = CorbaRequestGetResponseOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaRequestGetResponseOutId_Const,
			__goidl__.StructType,
			"CORBA_Request.idl",
			"xdl_CorbaRequestGetResponseOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaRequestGetResponseOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaRequestGetResponseOut{}
			},
			__reflect__.TypeOf((*CorbaRequestGetResponseOut)(nil))))
}
