// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::Context_delete_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaContextDeleteOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaContextDeleteOutId_Const = "IDL:CORBA/Context_delete_Out:1.0"

func (self *CorbaContextDeleteOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaContextDeleteOut) GoString() string {
	return self.String()
}

func (self *CorbaContextDeleteOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaContextDeleteOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaContextDeleteOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaContextDeleteOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaContextDeleteOutHelper = CorbaContextDeleteOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaContextDeleteOutId_Const,
			__goidl__.StructType,
			"CORBA_Context.idl",
			"xdl_CorbaContextDeleteOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaContextDeleteOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaContextDeleteOut{}
			},
			__reflect__.TypeOf((*CorbaContextDeleteOut)(nil))))
}
