// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::ArrayDef_destroy_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaArrayDefDestroyOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaArrayDefDestroyOutId_Const = "IDL:CORBA/ArrayDef_destroy_Out:1.0"

func (self *CorbaArrayDefDestroyOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaArrayDefDestroyOut) GoString() string {
	return self.String()
}

func (self *CorbaArrayDefDestroyOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaArrayDefDestroyOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaArrayDefDestroyOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaArrayDefDestroyOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaArrayDefDestroyOutHelper = CorbaArrayDefDestroyOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaArrayDefDestroyOutId_Const,
			__goidl__.StructType,
			"CORBA_InterfaceRepository.idl",
			"xdl_CorbaArrayDefDestroyOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaArrayDefDestroyOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaArrayDefDestroyOut{}
			},
			__reflect__.TypeOf((*CorbaArrayDefDestroyOut)(nil))))
}
