// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::RequestSeq", generatedBy by: "WriteStructSequenceDcl"
type CorbaRequestSeq struct {
	__goidl__.IdlObject
	Array []CorbaRequest `json:"Array"`
}

//noinspection GoSnakeCaseUsage
const CorbaRequestSeqId_Const = "IDL:CORBA/RequestSeq:1.0"

func (self *CorbaRequestSeq) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaRequestSeq) GoString() string {
	return self.String()
}

func (self *CorbaRequestSeq) ReadValue(stream __goidl__.IReadAny) error {
	return nil
}

func (self *CorbaRequestSeq) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaRequestSeq) Write(stream __goidl__.IWriteAny) error {
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaRequestSeq_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaRequestSeqHelper = CorbaRequestSeq_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaRequestSeqId_Const,
			__goidl__.SequenceType,
			"CORBA_ORB.idl",
			"xdl_CorbaRequestSeq.go",
			func() __goidl__.IIdlObject {
				return &CorbaRequestSeq{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaRequestSeq{}
			},
			__reflect__.TypeOf((*CorbaRequestSeq)(nil))))
}
