// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::TypeCode_discriminator_type_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaTypeCodeDiscriminatorTypeOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaTypeCodeDiscriminatorTypeOutId_Const = "IDL:CORBA/TypeCode_discriminator_type_Out:1.0"

func (self *CorbaTypeCodeDiscriminatorTypeOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaTypeCodeDiscriminatorTypeOut) GoString() string {
	return self.String()
}

func (self *CorbaTypeCodeDiscriminatorTypeOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaTypeCodeDiscriminatorTypeOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaTypeCodeDiscriminatorTypeOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaTypeCodeDiscriminatorTypeOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaTypeCodeDiscriminatorTypeOutHelper = CorbaTypeCodeDiscriminatorTypeOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaTypeCodeDiscriminatorTypeOutId_Const,
			__goidl__.StructType,
			"CORBA_TypeCode.idl",
			"xdl_CorbaTypeCodeDiscriminatorTypeOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaTypeCodeDiscriminatorTypeOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaTypeCodeDiscriminatorTypeOut{}
			},
			__reflect__.TypeOf((*CorbaTypeCodeDiscriminatorTypeOut)(nil))))
}
