// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"

// Interface declaration: "CORBA::ComponentIR::PublishesDef", generatedBy by: "WriteInterface"
type CorbaComponentIRPublishesDef interface {
	// Original name: "is_a"
	IsA(params CorbaComponentIRPublishesDefIsAIn) (CorbaComponentIRPublishesDefIsAOut, error)
}

const CorbaComponentIRPublishesDefIsAOperation = "is_a"
//noinspection GoSnakeCaseUsage
type CorbaComponentIRPublishesDef_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CorbaComponentIRPublishesDefId_Const = "IDL:omg.org/CORBA/ComponentIR/PublishesDef:1.0"

func (self CorbaComponentIRPublishesDef_Helper) Id() string {
	return CorbaComponentIRPublishesDefId_Const
}

func (self CorbaComponentIRPublishesDef_Helper) Read(stream __goidl__.IReadAny) (CorbaComponentIRPublishesDef, error) {
	return nil, nil
}

func (self CorbaComponentIRPublishesDef_Helper) Write(stream __goidl__.IWriteAny, v CorbaComponentIRPublishesDef) error {
	return nil
}


//noinspection GoUnusedGlobalVariable
var CorbaComponentIRPublishesDefHelper = CorbaComponentIRPublishesDef_Helper{}

func init() {
}
