// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::ServiceDetail", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaServiceDetail struct {
	__goidl__.IdlObject
	ServiceDetailType uint32 `json:"ServiceDetailType"`
	ServiceDetail CorbaServiceDetailData `json:"ServiceDetail"`
}

//noinspection GoSnakeCaseUsage
const CorbaServiceDetailId_Const = "IDL:omg.org/CORBA/ServiceDetail:1.0"

func (self *CorbaServiceDetail) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaServiceDetail) GoString() string {
	return self.String()
}

func (self *CorbaServiceDetail) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(UnsignedLongType)
	self.ServiceDetailType, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlStruct)
	err = self.ServiceDetail.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaServiceDetail) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaServiceDetail) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(UnsignedLongType)
	err = __goidl__.IdlUInt32Helper.Write(stream, self.ServiceDetailType)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlStruct)
	err = self.ServiceDetail.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaServiceDetail_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaServiceDetailHelper = CorbaServiceDetail_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaServiceDetailId_Const,
			__goidl__.StructType,
			"CORBA_ORB.idl",
			"xdl_CorbaServiceDetail.go",
			func() __goidl__.IIdlObject {
				return &CorbaServiceDetail{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaServiceDetail{}
			},
			__reflect__.TypeOf((*CorbaServiceDetail)(nil))))
}
