// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"

// Interface declaration: "CORBA::EnumDef", generatedBy by: "WriteInterface"
type CorbaEnumDef interface {
	// Original name: "destroy"
	Destroy(params CorbaEnumDefDestroyIn) (CorbaEnumDefDestroyOut, error)
	// Property Members
	// Get Property Members
	GetMembers() (CorbaEnumMemberSeq, error)
	// Set Property Members
	SetMembers(value CorbaEnumMemberSeq) error
}

const CorbaEnumDefDestroyOperation = "destroy"
//noinspection GoSnakeCaseUsage
type CorbaEnumDef_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CorbaEnumDefId_Const = "IDL:omg.org/CORBA/EnumDef:1.0"

func (self CorbaEnumDef_Helper) Id() string {
	return CorbaEnumDefId_Const
}

func (self CorbaEnumDef_Helper) Read(stream __goidl__.IReadAny) (CorbaEnumDef, error) {
	return nil, nil
}

func (self CorbaEnumDef_Helper) Write(stream __goidl__.IWriteAny, v CorbaEnumDef) error {
	return nil
}


//noinspection GoUnusedGlobalVariable
var CorbaEnumDefHelper = CorbaEnumDef_Helper{}

func init() {
}
