// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::ExceptionDef_create_union_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaExceptionDefCreateUnionOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaExceptionDefCreateUnionOutId_Const = "IDL:CORBA/ExceptionDef_create_union_Out:1.0"

func (self *CorbaExceptionDefCreateUnionOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaExceptionDefCreateUnionOut) GoString() string {
	return self.String()
}

func (self *CorbaExceptionDefCreateUnionOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaExceptionDefCreateUnionOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaExceptionDefCreateUnionOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaExceptionDefCreateUnionOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaExceptionDefCreateUnionOutHelper = CorbaExceptionDefCreateUnionOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaExceptionDefCreateUnionOutId_Const,
			__goidl__.StructType,
			"CORBA_InterfaceRepository.idl",
			"xdl_CorbaExceptionDefCreateUnionOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaExceptionDefCreateUnionOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaExceptionDefCreateUnionOut{}
			},
			__reflect__.TypeOf((*CorbaExceptionDefCreateUnionOut)(nil))))
}
