// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::ORB_string_to_object_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaOrbStringToObjectOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaOrbStringToObjectOutId_Const = "IDL:CORBA/ORB_string_to_object_Out:1.0"

func (self *CorbaOrbStringToObjectOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaOrbStringToObjectOut) GoString() string {
	return self.String()
}

func (self *CorbaOrbStringToObjectOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaOrbStringToObjectOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaOrbStringToObjectOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaOrbStringToObjectOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaOrbStringToObjectOutHelper = CorbaOrbStringToObjectOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaOrbStringToObjectOutId_Const,
			__goidl__.StructType,
			"CORBA_ORB.idl",
			"xdl_CorbaOrbStringToObjectOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaOrbStringToObjectOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaOrbStringToObjectOut{}
			},
			__reflect__.TypeOf((*CorbaOrbStringToObjectOut)(nil))))
}
