// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"

// Interface declaration: "CORBA::ModuleDef", generatedBy by: "WriteInterface"
type CorbaModuleDef interface {
	// Original name: "contents"
	Contents(params CorbaModuleDefContentsIn) (CorbaModuleDefContentsOut, error)
	// Original name: "create_abstract_interface"
	CreateAbstractInterface(params CorbaModuleDefCreateAbstractInterfaceIn) (CorbaModuleDefCreateAbstractInterfaceOut, error)
	// Original name: "create_alias"
	CreateAlias(params CorbaModuleDefCreateAliasIn) (CorbaModuleDefCreateAliasOut, error)
	// Original name: "create_constant"
	CreateConstant(params CorbaModuleDefCreateConstantIn) (CorbaModuleDefCreateConstantOut, error)
	// Original name: "create_enum"
	CreateEnum(params CorbaModuleDefCreateEnumIn) (CorbaModuleDefCreateEnumOut, error)
	// Original name: "create_exception"
	CreateException(params CorbaModuleDefCreateExceptionIn) (CorbaModuleDefCreateExceptionOut, error)
	// Original name: "create_ext_value"
	CreateExtValue(params CorbaModuleDefCreateExtValueIn) (CorbaModuleDefCreateExtValueOut, error)
	// Original name: "create_interface"
	CreateInterface(params CorbaModuleDefCreateInterfaceIn) (CorbaModuleDefCreateInterfaceOut, error)
	// Original name: "create_local_interface"
	CreateLocalInterface(params CorbaModuleDefCreateLocalInterfaceIn) (CorbaModuleDefCreateLocalInterfaceOut, error)
	// Original name: "create_module"
	CreateModule(params CorbaModuleDefCreateModuleIn) (CorbaModuleDefCreateModuleOut, error)
	// Original name: "create_native"
	CreateNative(params CorbaModuleDefCreateNativeIn) (CorbaModuleDefCreateNativeOut, error)
	// Original name: "create_struct"
	CreateStruct(params CorbaModuleDefCreateStructIn) (CorbaModuleDefCreateStructOut, error)
	// Original name: "create_union"
	CreateUnion(params CorbaModuleDefCreateUnionIn) (CorbaModuleDefCreateUnionOut, error)
	// Original name: "create_value"
	CreateValue(params CorbaModuleDefCreateValueIn) (CorbaModuleDefCreateValueOut, error)
	// Original name: "create_value_box"
	CreateValueBox(params CorbaModuleDefCreateValueBoxIn) (CorbaModuleDefCreateValueBoxOut, error)
	// Original name: "describe_contents"
	DescribeContents(params CorbaModuleDefDescribeContentsIn) (CorbaModuleDefDescribeContentsOut, error)
	// Original name: "destroy"
	Destroy(params CorbaModuleDefDestroyIn) (CorbaModuleDefDestroyOut, error)
	// Original name: "lookup"
	Lookup(params CorbaModuleDefLookupIn) (CorbaModuleDefLookupOut, error)
	// Original name: "lookup_name"
	LookupName(params CorbaModuleDefLookupNameIn) (CorbaModuleDefLookupNameOut, error)
}

const CorbaModuleDefContentsOperation = "contents"
const CorbaModuleDefCreateAbstractInterfaceOperation = "create_abstract_interface"
const CorbaModuleDefCreateAliasOperation = "create_alias"
const CorbaModuleDefCreateConstantOperation = "create_constant"
const CorbaModuleDefCreateEnumOperation = "create_enum"
const CorbaModuleDefCreateExceptionOperation = "create_exception"
const CorbaModuleDefCreateExtValueOperation = "create_ext_value"
const CorbaModuleDefCreateInterfaceOperation = "create_interface"
const CorbaModuleDefCreateLocalInterfaceOperation = "create_local_interface"
const CorbaModuleDefCreateModuleOperation = "create_module"
const CorbaModuleDefCreateNativeOperation = "create_native"
const CorbaModuleDefCreateStructOperation = "create_struct"
const CorbaModuleDefCreateUnionOperation = "create_union"
const CorbaModuleDefCreateValueOperation = "create_value"
const CorbaModuleDefCreateValueBoxOperation = "create_value_box"
const CorbaModuleDefDescribeContentsOperation = "describe_contents"
const CorbaModuleDefDestroyOperation = "destroy"
const CorbaModuleDefLookupOperation = "lookup"
const CorbaModuleDefLookupNameOperation = "lookup_name"
//noinspection GoSnakeCaseUsage
type CorbaModuleDef_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CorbaModuleDefId_Const = "IDL:omg.org/CORBA/ModuleDef:1.0"

func (self CorbaModuleDef_Helper) Id() string {
	return CorbaModuleDefId_Const
}

func (self CorbaModuleDef_Helper) Read(stream __goidl__.IReadAny) (CorbaModuleDef, error) {
	return nil, nil
}

func (self CorbaModuleDef_Helper) Write(stream __goidl__.IWriteAny, v CorbaModuleDef) error {
	return nil
}


//noinspection GoUnusedGlobalVariable
var CorbaModuleDefHelper = CorbaModuleDef_Helper{}

func init() {
}
