// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::NVList_get_count_In", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaNVListGetCountIn struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaNVListGetCountInId_Const = "IDL:CORBA/NVList_get_count_In:1.0"

func (self *CorbaNVListGetCountIn) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaNVListGetCountIn) GoString() string {
	return self.String()
}

func (self *CorbaNVListGetCountIn) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaNVListGetCountIn) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaNVListGetCountIn) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaNVListGetCountIn_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaNVListGetCountInHelper = CorbaNVListGetCountIn_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaNVListGetCountInId_Const,
			__goidl__.StructType,
			"CORBA_NVList.idl",
			"xdl_CorbaNVListGetCountIn.go",
			func() __goidl__.IIdlObject {
				return &CorbaNVListGetCountIn{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaNVListGetCountIn{}
			},
			__reflect__.TypeOf((*CorbaNVListGetCountIn)(nil))))
}
