// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::ExtLocalInterfaceDef_create_value_box_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaExtLocalInterfaceDefCreateValueBoxOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaExtLocalInterfaceDefCreateValueBoxOutId_Const = "IDL:CORBA/ExtLocalInterfaceDef_create_value_box_Out:1.0"

func (self *CorbaExtLocalInterfaceDefCreateValueBoxOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaExtLocalInterfaceDefCreateValueBoxOut) GoString() string {
	return self.String()
}

func (self *CorbaExtLocalInterfaceDefCreateValueBoxOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaExtLocalInterfaceDefCreateValueBoxOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaExtLocalInterfaceDefCreateValueBoxOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaExtLocalInterfaceDefCreateValueBoxOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaExtLocalInterfaceDefCreateValueBoxOutHelper = CorbaExtLocalInterfaceDefCreateValueBoxOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaExtLocalInterfaceDefCreateValueBoxOutId_Const,
			__goidl__.StructType,
			"CORBA_InterfaceRepository.idl",
			"xdl_CorbaExtLocalInterfaceDefCreateValueBoxOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaExtLocalInterfaceDefCreateValueBoxOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaExtLocalInterfaceDefCreateValueBoxOut{}
			},
			__reflect__.TypeOf((*CorbaExtLocalInterfaceDefCreateValueBoxOut)(nil))))
}
