// Code generated by me. DO NOT EDIT.

package goIdlCorba

// Struct declaration: "CORBA::PolicyCurrent_Stub", generatedBy by: "WriteStructDcl"
type CorbaPolicyCurrentStub struct {
}


func init() {
}
