// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::Request_send_In", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaRequestSendIn struct {
	__goidl__.IdlObject
	InvokeFlags uint32 `json:"InvokeFlags"`
}

//noinspection GoSnakeCaseUsage
const CorbaRequestSendInId_Const = "IDL:CORBA/Request_send_In:1.0"

func (self *CorbaRequestSendIn) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaRequestSendIn) GoString() string {
	return self.String()
}

func (self *CorbaRequestSendIn) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(UnsignedLongType)
	self.InvokeFlags, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaRequestSendIn) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaRequestSendIn) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(UnsignedLongType)
	err = __goidl__.IdlUInt32Helper.Write(stream, self.InvokeFlags)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaRequestSendIn_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaRequestSendInHelper = CorbaRequestSendIn_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaRequestSendInId_Const,
			__goidl__.StructType,
			"CORBA_Request.idl",
			"xdl_CorbaRequestSendIn.go",
			func() __goidl__.IIdlObject {
				return &CorbaRequestSendIn{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaRequestSendIn{}
			},
			__reflect__.TypeOf((*CorbaRequestSendIn)(nil))))
}
