// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::ModuleDef_create_value_box_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaModuleDefCreateValueBoxOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaModuleDefCreateValueBoxOutId_Const = "IDL:CORBA/ModuleDef_create_value_box_Out:1.0"

func (self *CorbaModuleDefCreateValueBoxOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaModuleDefCreateValueBoxOut) GoString() string {
	return self.String()
}

func (self *CorbaModuleDefCreateValueBoxOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaModuleDefCreateValueBoxOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaModuleDefCreateValueBoxOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaModuleDefCreateValueBoxOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaModuleDefCreateValueBoxOutHelper = CorbaModuleDefCreateValueBoxOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaModuleDefCreateValueBoxOutId_Const,
			__goidl__.StructType,
			"CORBA_InterfaceRepository.idl",
			"xdl_CorbaModuleDefCreateValueBoxOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaModuleDefCreateValueBoxOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaModuleDefCreateValueBoxOut{}
			},
			__reflect__.TypeOf((*CorbaModuleDefCreateValueBoxOut)(nil))))
}
