// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::ConstructionPolicy_copy_In", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaConstructionPolicyCopyIn struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaConstructionPolicyCopyInId_Const = "IDL:CORBA/ConstructionPolicy_copy_In:1.0"

func (self *CorbaConstructionPolicyCopyIn) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaConstructionPolicyCopyIn) GoString() string {
	return self.String()
}

func (self *CorbaConstructionPolicyCopyIn) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaConstructionPolicyCopyIn) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaConstructionPolicyCopyIn) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaConstructionPolicyCopyIn_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaConstructionPolicyCopyInHelper = CorbaConstructionPolicyCopyIn_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaConstructionPolicyCopyInId_Const,
			__goidl__.StructType,
			"CORBA_DomainManager.idl",
			"xdl_CorbaConstructionPolicyCopyIn.go",
			func() __goidl__.IIdlObject {
				return &CorbaConstructionPolicyCopyIn{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaConstructionPolicyCopyIn{}
			},
			__reflect__.TypeOf((*CorbaConstructionPolicyCopyIn)(nil))))
}
