// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::Context_delete_values_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaContextDeleteValuesOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaContextDeleteValuesOutId_Const = "IDL:CORBA/Context_delete_values_Out:1.0"

func (self *CorbaContextDeleteValuesOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaContextDeleteValuesOut) GoString() string {
	return self.String()
}

func (self *CorbaContextDeleteValuesOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaContextDeleteValuesOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaContextDeleteValuesOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaContextDeleteValuesOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaContextDeleteValuesOutHelper = CorbaContextDeleteValuesOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaContextDeleteValuesOutId_Const,
			__goidl__.StructType,
			"CORBA_Context.idl",
			"xdl_CorbaContextDeleteValuesOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaContextDeleteValuesOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaContextDeleteValuesOut{}
			},
			__reflect__.TypeOf((*CorbaContextDeleteValuesOut)(nil))))
}
