// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::ExtValueDef_create_operation_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaExtValueDefCreateOperationOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaExtValueDefCreateOperationOutId_Const = "IDL:CORBA/ExtValueDef_create_operation_Out:1.0"

func (self *CorbaExtValueDefCreateOperationOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaExtValueDefCreateOperationOut) GoString() string {
	return self.String()
}

func (self *CorbaExtValueDefCreateOperationOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaExtValueDefCreateOperationOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaExtValueDefCreateOperationOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaExtValueDefCreateOperationOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaExtValueDefCreateOperationOutHelper = CorbaExtValueDefCreateOperationOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaExtValueDefCreateOperationOutId_Const,
			__goidl__.StructType,
			"CORBA_InterfaceRepository.idl",
			"xdl_CorbaExtValueDefCreateOperationOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaExtValueDefCreateOperationOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaExtValueDefCreateOperationOut{}
			},
			__reflect__.TypeOf((*CorbaExtValueDefCreateOperationOut)(nil))))
}
