// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::ORB_register_initial_reference_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaOrbRegisterInitialReferenceOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaOrbRegisterInitialReferenceOutId_Const = "IDL:CORBA/ORB_register_initial_reference_Out:1.0"

func (self *CorbaOrbRegisterInitialReferenceOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaOrbRegisterInitialReferenceOut) GoString() string {
	return self.String()
}

func (self *CorbaOrbRegisterInitialReferenceOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaOrbRegisterInitialReferenceOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaOrbRegisterInitialReferenceOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaOrbRegisterInitialReferenceOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaOrbRegisterInitialReferenceOutHelper = CorbaOrbRegisterInitialReferenceOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaOrbRegisterInitialReferenceOutId_Const,
			__goidl__.StructType,
			"CORBA_ORB.idl",
			"xdl_CorbaOrbRegisterInitialReferenceOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaOrbRegisterInitialReferenceOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaOrbRegisterInitialReferenceOut{}
			},
			__reflect__.TypeOf((*CorbaOrbRegisterInitialReferenceOut)(nil))))
}
