// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"

// Interface declaration: "CORBA::Contained", generatedBy by: "WriteInterface"
type CorbaContained interface {
}

//noinspection GoSnakeCaseUsage
type CorbaContained_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CorbaContainedId_Const = "IDL:omg.org/CORBA/Contained:1.0"

func (self CorbaContained_Helper) Id() string {
	return CorbaContainedId_Const
}

func (self CorbaContained_Helper) Read(stream __goidl__.IReadAny) (CorbaContained, error) {
	return nil, nil
}

func (self CorbaContained_Helper) Write(stream __goidl__.IWriteAny, v CorbaContained) error {
	return nil
}


//noinspection GoUnusedGlobalVariable
var CorbaContainedHelper = CorbaContained_Helper{}

func init() {
}
