// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::ORB_get_default_context_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaOrbGetDefaultContextOut struct {
	__goidl__.IdlObject
	Ctx CorbaContext `json:"Ctx"`
}

//noinspection GoSnakeCaseUsage
const CorbaOrbGetDefaultContextOutId_Const = "IDL:CORBA/ORB_get_default_context_Out:1.0"

func (self *CorbaOrbGetDefaultContextOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaOrbGetDefaultContextOut) GoString() string {
	return self.String()
}

func (self *CorbaOrbGetDefaultContextOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlInterface)
	self.Ctx, err = CorbaContextHelper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaOrbGetDefaultContextOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaOrbGetDefaultContextOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlInterface)
	err = CorbaContextHelper.Write(stream, self.Ctx)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaOrbGetDefaultContextOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaOrbGetDefaultContextOutHelper = CorbaOrbGetDefaultContextOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaOrbGetDefaultContextOutId_Const,
			__goidl__.StructType,
			"CORBA_ORB.idl",
			"xdl_CorbaOrbGetDefaultContextOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaOrbGetDefaultContextOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaOrbGetDefaultContextOut{}
			},
			__reflect__.TypeOf((*CorbaOrbGetDefaultContextOut)(nil))))
}
