// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::ComponentIR::EventDef_lookup_name_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaComponentIREventDefLookupNameOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaComponentIREventDefLookupNameOutId_Const = "IDL:CORBA/ComponentIR/EventDef_lookup_name_Out:1.0"

func (self *CorbaComponentIREventDefLookupNameOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaComponentIREventDefLookupNameOut) GoString() string {
	return self.String()
}

func (self *CorbaComponentIREventDefLookupNameOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaComponentIREventDefLookupNameOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaComponentIREventDefLookupNameOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaComponentIREventDefLookupNameOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaComponentIREventDefLookupNameOutHelper = CorbaComponentIREventDefLookupNameOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaComponentIREventDefLookupNameOutId_Const,
			__goidl__.StructType,
			"CORBA_InterfaceRepository.idl",
			"xdl_CorbaComponentIREventDefLookupNameOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaComponentIREventDefLookupNameOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaComponentIREventDefLookupNameOut{}
			},
			__reflect__.TypeOf((*CorbaComponentIREventDefLookupNameOut)(nil))))
}
