// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::PolicyCurrent_get_policy_overrides_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaPolicyCurrentGetPolicyOverridesOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaPolicyCurrentGetPolicyOverridesOutId_Const = "IDL:CORBA/PolicyCurrent_get_policy_overrides_Out:1.0"

func (self *CorbaPolicyCurrentGetPolicyOverridesOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaPolicyCurrentGetPolicyOverridesOut) GoString() string {
	return self.String()
}

func (self *CorbaPolicyCurrentGetPolicyOverridesOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaPolicyCurrentGetPolicyOverridesOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaPolicyCurrentGetPolicyOverridesOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaPolicyCurrentGetPolicyOverridesOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaPolicyCurrentGetPolicyOverridesOutHelper = CorbaPolicyCurrentGetPolicyOverridesOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaPolicyCurrentGetPolicyOverridesOutId_Const,
			__goidl__.StructType,
			"CORBA_Policy.idl",
			"xdl_CorbaPolicyCurrentGetPolicyOverridesOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaPolicyCurrentGetPolicyOverridesOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaPolicyCurrentGetPolicyOverridesOut{}
			},
			__reflect__.TypeOf((*CorbaPolicyCurrentGetPolicyOverridesOut)(nil))))
}
