// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::Container::DescriptionSeq", generatedBy by: "WriteStructSequenceDcl"
type CorbaContainerDescriptionSeq struct {
	__goidl__.IdlObject
	Array []*CorbaContainerDescription `json:"Array"`
}

//noinspection GoSnakeCaseUsage
const CorbaContainerDescriptionSeqId_Const = "IDL:CORBA/Container/DescriptionSeq:1.0"

func (self *CorbaContainerDescriptionSeq) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaContainerDescriptionSeq) GoString() string {
	return self.String()
}

func (self *CorbaContainerDescriptionSeq) ReadValue(stream __goidl__.IReadAny) error {
	err := self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	var n uint32
	n, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	if n > 0 {
		self.Array = make([]*CorbaContainerDescription, n)
		var i uint32
		for i = 0; i < n; i++ {
			self.Array[i] = &CorbaContainerDescription{}
			err = self.Array[i].ReadValue(stream)
				if err != nil {
				return err
			}
		}
	}
	return nil
}

func (self *CorbaContainerDescriptionSeq) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaContainerDescriptionSeq) Write(stream __goidl__.IWriteAny) error {
	err := self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	err = __goidl__.IdlUInt32Helper.Write(stream, uint32(len(self.Array)))
	if err != nil {
	return err
	}
	if len(self.Array) > 0 {
		for _, item := range self.Array {
			err = item.Write(stream)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaContainerDescriptionSeq_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaContainerDescriptionSeqHelper = CorbaContainerDescriptionSeq_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaContainerDescriptionSeqId_Const,
			__goidl__.SequenceType,
			"CORBA_InterfaceRepository.idl",
			"xdl_CorbaContainerDescriptionSeq.go",
			func() __goidl__.IIdlObject {
				return &CorbaContainerDescriptionSeq{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaContainerDescriptionSeq{}
			},
			__reflect__.TypeOf((*CorbaContainerDescriptionSeq)(nil))))
}
