// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::Request_sendc_In", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaRequestSendcIn struct {
	__goidl__.IdlObject
	Handler __goidl__.IIdlObject `json:"Handler"`
}

//noinspection GoSnakeCaseUsage
const CorbaRequestSendcInId_Const = "IDL:CORBA/Request_sendc_In:1.0"

func (self *CorbaRequestSendcIn) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaRequestSendcIn) GoString() string {
	return self.String()
}

func (self *CorbaRequestSendcIn) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(IdlObjectKind)
	self.Handler, err = __goidl__.IdlObjectHelper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaRequestSendcIn) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaRequestSendcIn) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(IdlObjectKind)
	err = __goidl__.IdlObjectHelper.Write(stream, self.Handler)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaRequestSendcIn_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaRequestSendcInHelper = CorbaRequestSendcIn_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaRequestSendcInId_Const,
			__goidl__.StructType,
			"CORBA_Request.idl",
			"xdl_CorbaRequestSendcIn.go",
			func() __goidl__.IIdlObject {
				return &CorbaRequestSendcIn{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaRequestSendcIn{}
			},
			__reflect__.TypeOf((*CorbaRequestSendcIn)(nil))))
}
