// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"

// Interface declaration: "CORBA::NVList", generatedBy by: "WriteInterface"
type CorbaNVList interface {
	// Original name: "add_item"
	AddItem(params CorbaNVListAddItemIn) (CorbaNVListAddItemOut, error)
	// Original name: "free"
	Free(params CorbaNVListFreeIn) (CorbaNVListFreeOut, error)
	// Original name: "free_memory"
	FreeMemory(params CorbaNVListFreeMemoryIn) (CorbaNVListFreeMemoryOut, error)
	// Original name: "get_count"
	GetCount(params CorbaNVListGetCountIn) (CorbaNVListGetCountOut, error)
}

const CorbaNVListAddItemOperation = "add_item"
const CorbaNVListFreeOperation = "free"
const CorbaNVListFreeMemoryOperation = "free_memory"
const CorbaNVListGetCountOperation = "get_count"
//noinspection GoSnakeCaseUsage
type CorbaNVList_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CorbaNVListId_Const = "IDL:omg.org/CORBA/NVList:1.0"

func (self CorbaNVList_Helper) Id() string {
	return CorbaNVListId_Const
}

func (self CorbaNVList_Helper) Read(stream __goidl__.IReadAny) (CorbaNVList, error) {
	return nil, nil
}

func (self CorbaNVList_Helper) Write(stream __goidl__.IWriteAny, v CorbaNVList) error {
	return nil
}


//noinspection GoUnusedGlobalVariable
var CorbaNVListHelper = CorbaNVList_Helper{}

func init() {
}
