// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::Policy_copy_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaPolicyCopyOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaPolicyCopyOutId_Const = "IDL:CORBA/Policy_copy_Out:1.0"

func (self *CorbaPolicyCopyOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaPolicyCopyOut) GoString() string {
	return self.String()
}

func (self *CorbaPolicyCopyOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaPolicyCopyOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaPolicyCopyOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaPolicyCopyOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaPolicyCopyOutHelper = CorbaPolicyCopyOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaPolicyCopyOutId_Const,
			__goidl__.StructType,
			"CORBA_Policy.idl",
			"xdl_CorbaPolicyCopyOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaPolicyCopyOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaPolicyCopyOut{}
			},
			__reflect__.TypeOf((*CorbaPolicyCopyOut)(nil))))
}
