// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::TypeCode_name_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaTypeCodeNameOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaTypeCodeNameOutId_Const = "IDL:CORBA/TypeCode_name_Out:1.0"

func (self *CorbaTypeCodeNameOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaTypeCodeNameOut) GoString() string {
	return self.String()
}

func (self *CorbaTypeCodeNameOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaTypeCodeNameOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaTypeCodeNameOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaTypeCodeNameOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaTypeCodeNameOutHelper = CorbaTypeCodeNameOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaTypeCodeNameOutId_Const,
			__goidl__.StructType,
			"CORBA_TypeCode.idl",
			"xdl_CorbaTypeCodeNameOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaTypeCodeNameOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaTypeCodeNameOut{}
			},
			__reflect__.TypeOf((*CorbaTypeCodeNameOut)(nil))))
}
