// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::Container_create_value_box_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaContainerCreateValueBoxOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaContainerCreateValueBoxOutId_Const = "IDL:CORBA/Container_create_value_box_Out:1.0"

func (self *CorbaContainerCreateValueBoxOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaContainerCreateValueBoxOut) GoString() string {
	return self.String()
}

func (self *CorbaContainerCreateValueBoxOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaContainerCreateValueBoxOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaContainerCreateValueBoxOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaContainerCreateValueBoxOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaContainerCreateValueBoxOutHelper = CorbaContainerCreateValueBoxOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaContainerCreateValueBoxOutId_Const,
			__goidl__.StructType,
			"CORBA_InterfaceRepository.idl",
			"xdl_CorbaContainerCreateValueBoxOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaContainerCreateValueBoxOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaContainerCreateValueBoxOut{}
			},
			__reflect__.TypeOf((*CorbaContainerCreateValueBoxOut)(nil))))
}
