// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"

// Interface declaration: "CORBA::ExtAttributeDef", generatedBy by: "WriteInterface"
type CorbaExtAttributeDef interface {
	// Original name: "describe_attribute"
	DescribeAttribute(params CorbaExtAttributeDefDescribeAttributeIn) (CorbaExtAttributeDefDescribeAttributeOut, error)
	// Property GetExceptions
	// Get Property GetExceptions
	GetGetExceptions() (CorbaExcDescriptionSeq, error)
	// Set Property GetExceptions
	SetGetExceptions(value CorbaExcDescriptionSeq) error
	// Property SetExceptions
	// Get Property SetExceptions
	GetSetExceptions() (CorbaExcDescriptionSeq, error)
	// Set Property SetExceptions
	SetSetExceptions(value CorbaExcDescriptionSeq) error
}

const CorbaExtAttributeDefDescribeAttributeOperation = "describe_attribute"
//noinspection GoSnakeCaseUsage
type CorbaExtAttributeDef_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CorbaExtAttributeDefId_Const = "IDL:omg.org/CORBA/ExtAttributeDef:1.0"

func (self CorbaExtAttributeDef_Helper) Id() string {
	return CorbaExtAttributeDefId_Const
}

func (self CorbaExtAttributeDef_Helper) Read(stream __goidl__.IReadAny) (CorbaExtAttributeDef, error) {
	return nil, nil
}

func (self CorbaExtAttributeDef_Helper) Write(stream __goidl__.IWriteAny, v CorbaExtAttributeDef) error {
	return nil
}


//noinspection GoUnusedGlobalVariable
var CorbaExtAttributeDefHelper = CorbaExtAttributeDef_Helper{}

func init() {
}
