// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::InterfaceDef_is_a_In", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaInterfaceDefIsAIn struct {
	__goidl__.IdlObject
	InterfaceId string `json:"InterfaceId"`
}

//noinspection GoSnakeCaseUsage
const CorbaInterfaceDefIsAInId_Const = "IDL:CORBA/InterfaceDef_is_a_In:1.0"

func (self *CorbaInterfaceDefIsAIn) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaInterfaceDefIsAIn) GoString() string {
	return self.String()
}

func (self *CorbaInterfaceDefIsAIn) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(StringType)
	self.InterfaceId, err = __goidl__.IdlStringHelper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaInterfaceDefIsAIn) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaInterfaceDefIsAIn) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(StringType)
	err = __goidl__.IdlStringHelper.Write(stream, self.InterfaceId)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaInterfaceDefIsAIn_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaInterfaceDefIsAInHelper = CorbaInterfaceDefIsAIn_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaInterfaceDefIsAInId_Const,
			__goidl__.StructType,
			"CORBA_InterfaceRepository.idl",
			"xdl_CorbaInterfaceDefIsAIn.go",
			func() __goidl__.IIdlObject {
				return &CorbaInterfaceDefIsAIn{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaInterfaceDefIsAIn{}
			},
			__reflect__.TypeOf((*CorbaInterfaceDefIsAIn)(nil))))
}
