// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::Request_invoke_In", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaRequestInvokeIn struct {
	__goidl__.IdlObject
	InvokeFlags uint32 `json:"InvokeFlags"`
}

//noinspection GoSnakeCaseUsage
const CorbaRequestInvokeInId_Const = "IDL:CORBA/Request_invoke_In:1.0"

func (self *CorbaRequestInvokeIn) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaRequestInvokeIn) GoString() string {
	return self.String()
}

func (self *CorbaRequestInvokeIn) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(UnsignedLongType)
	self.InvokeFlags, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaRequestInvokeIn) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaRequestInvokeIn) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(UnsignedLongType)
	err = __goidl__.IdlUInt32Helper.Write(stream, self.InvokeFlags)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaRequestInvokeIn_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaRequestInvokeInHelper = CorbaRequestInvokeIn_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaRequestInvokeInId_Const,
			__goidl__.StructType,
			"CORBA_Request.idl",
			"xdl_CorbaRequestInvokeIn.go",
			func() __goidl__.IIdlObject {
				return &CorbaRequestInvokeIn{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaRequestInvokeIn{}
			},
			__reflect__.TypeOf((*CorbaRequestInvokeIn)(nil))))
}
