// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::ORB_create_wstring_tc_In", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaOrbCreateWstringTcIn struct {
	__goidl__.IdlObject
	Bound uint32 `json:"Bound"`
}

//noinspection GoSnakeCaseUsage
const CorbaOrbCreateWstringTcInId_Const = "IDL:CORBA/ORB_create_wstring_tc_In:1.0"

func (self *CorbaOrbCreateWstringTcIn) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaOrbCreateWstringTcIn) GoString() string {
	return self.String()
}

func (self *CorbaOrbCreateWstringTcIn) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberExtractValue(UnsignedLongType)
	self.Bound, err = __goidl__.IdlUInt32Helper.Read(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaOrbCreateWstringTcIn) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaOrbCreateWstringTcIn) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	// WriteStructHelper::WriteStructMemberInsert(UnsignedLongType)
	err = __goidl__.IdlUInt32Helper.Write(stream, self.Bound)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaOrbCreateWstringTcIn_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaOrbCreateWstringTcInHelper = CorbaOrbCreateWstringTcIn_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaOrbCreateWstringTcInId_Const,
			__goidl__.StructType,
			"CORBA_ORB.idl",
			"xdl_CorbaOrbCreateWstringTcIn.go",
			func() __goidl__.IIdlObject {
				return &CorbaOrbCreateWstringTcIn{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaOrbCreateWstringTcIn{}
			},
			__reflect__.TypeOf((*CorbaOrbCreateWstringTcIn)(nil))))
}
