// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::Container_describe_contents_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaContainerDescribeContentsOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaContainerDescribeContentsOutId_Const = "IDL:CORBA/Container_describe_contents_Out:1.0"

func (self *CorbaContainerDescribeContentsOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaContainerDescribeContentsOut) GoString() string {
	return self.String()
}

func (self *CorbaContainerDescribeContentsOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaContainerDescribeContentsOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaContainerDescribeContentsOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaContainerDescribeContentsOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaContainerDescribeContentsOutHelper = CorbaContainerDescribeContentsOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaContainerDescribeContentsOutId_Const,
			__goidl__.StructType,
			"CORBA_InterfaceRepository.idl",
			"xdl_CorbaContainerDescribeContentsOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaContainerDescribeContentsOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaContainerDescribeContentsOut{}
			},
			__reflect__.TypeOf((*CorbaContainerDescribeContentsOut)(nil))))
}
