// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::Request_prepare_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaRequestPrepareOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaRequestPrepareOutId_Const = "IDL:CORBA/Request_prepare_Out:1.0"

func (self *CorbaRequestPrepareOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaRequestPrepareOut) GoString() string {
	return self.String()
}

func (self *CorbaRequestPrepareOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaRequestPrepareOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaRequestPrepareOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaRequestPrepareOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaRequestPrepareOutHelper = CorbaRequestPrepareOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaRequestPrepareOutId_Const,
			__goidl__.StructType,
			"CORBA_Request.idl",
			"xdl_CorbaRequestPrepareOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaRequestPrepareOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaRequestPrepareOut{}
			},
			__reflect__.TypeOf((*CorbaRequestPrepareOut)(nil))))
}
