// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"

// Interface declaration: "CORBA::ComponentIR::ProvidesDef", generatedBy by: "WriteInterface"
type CorbaComponentIRProvidesDef interface {
	// Property InterfaceType
	// Get Property InterfaceType
	GetInterfaceType() (CorbaInterfaceDef, error)
	// Set Property InterfaceType
	SetInterfaceType(value CorbaInterfaceDef) error
}

//noinspection GoSnakeCaseUsage
type CorbaComponentIRProvidesDef_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CorbaComponentIRProvidesDefId_Const = "IDL:omg.org/CORBA/ComponentIR/ProvidesDef:1.0"

func (self CorbaComponentIRProvidesDef_Helper) Id() string {
	return CorbaComponentIRProvidesDefId_Const
}

func (self CorbaComponentIRProvidesDef_Helper) Read(stream __goidl__.IReadAny) (CorbaComponentIRProvidesDef, error) {
	return nil, nil
}

func (self CorbaComponentIRProvidesDef_Helper) Write(stream __goidl__.IWriteAny, v CorbaComponentIRProvidesDef) error {
	return nil
}


//noinspection GoUnusedGlobalVariable
var CorbaComponentIRProvidesDefHelper = CorbaComponentIRProvidesDef_Helper{}

func init() {
}
