// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::Policy_destroy_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaPolicyDestroyOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaPolicyDestroyOutId_Const = "IDL:CORBA/Policy_destroy_Out:1.0"

func (self *CorbaPolicyDestroyOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaPolicyDestroyOut) GoString() string {
	return self.String()
}

func (self *CorbaPolicyDestroyOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaPolicyDestroyOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaPolicyDestroyOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaPolicyDestroyOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaPolicyDestroyOutHelper = CorbaPolicyDestroyOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaPolicyDestroyOutId_Const,
			__goidl__.StructType,
			"CORBA_Policy.idl",
			"xdl_CorbaPolicyDestroyOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaPolicyDestroyOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaPolicyDestroyOut{}
			},
			__reflect__.TypeOf((*CorbaPolicyDestroyOut)(nil))))
}
