// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::NVList_add_item_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaNVListAddItemOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaNVListAddItemOutId_Const = "IDL:CORBA/NVList_add_item_Out:1.0"

func (self *CorbaNVListAddItemOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaNVListAddItemOut) GoString() string {
	return self.String()
}

func (self *CorbaNVListAddItemOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaNVListAddItemOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaNVListAddItemOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaNVListAddItemOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaNVListAddItemOutHelper = CorbaNVListAddItemOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaNVListAddItemOutId_Const,
			__goidl__.StructType,
			"CORBA_NVList.idl",
			"xdl_CorbaNVListAddItemOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaNVListAddItemOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaNVListAddItemOut{}
			},
			__reflect__.TypeOf((*CorbaNVListAddItemOut)(nil))))
}
