// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"

// Interface declaration: "CORBA::IRObject", generatedBy by: "WriteInterface"
type CorbaIRObject interface {
	// Original name: "destroy"
	Destroy(params CorbaIRObjectDestroyIn) (CorbaIRObjectDestroyOut, error)
	// Property DefKind
	// Get Property DefKind
	GetDefKind() (uint32, error)
}

const CorbaIRObjectDestroyOperation = "destroy"
//noinspection GoSnakeCaseUsage
type CorbaIRObject_Helper struct {
}

//noinspection GoSnakeCaseUsage
const CorbaIRObjectId_Const = "IDL:omg.org/CORBA/IRObject:1.0"

func (self CorbaIRObject_Helper) Id() string {
	return CorbaIRObjectId_Const
}

func (self CorbaIRObject_Helper) Read(stream __goidl__.IReadAny) (CorbaIRObject, error) {
	return nil, nil
}

func (self CorbaIRObject_Helper) Write(stream __goidl__.IWriteAny, v CorbaIRObject) error {
	return nil
}


//noinspection GoUnusedGlobalVariable
var CorbaIRObjectHelper = CorbaIRObject_Helper{}

func init() {
}
