// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::ExceptionDef_create_alias_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaExceptionDefCreateAliasOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaExceptionDefCreateAliasOutId_Const = "IDL:CORBA/ExceptionDef_create_alias_Out:1.0"

func (self *CorbaExceptionDefCreateAliasOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaExceptionDefCreateAliasOut) GoString() string {
	return self.String()
}

func (self *CorbaExceptionDefCreateAliasOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaExceptionDefCreateAliasOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaExceptionDefCreateAliasOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaExceptionDefCreateAliasOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaExceptionDefCreateAliasOutHelper = CorbaExceptionDefCreateAliasOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaExceptionDefCreateAliasOutId_Const,
			__goidl__.StructType,
			"CORBA_InterfaceRepository.idl",
			"xdl_CorbaExceptionDefCreateAliasOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaExceptionDefCreateAliasOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaExceptionDefCreateAliasOut{}
			},
			__reflect__.TypeOf((*CorbaExceptionDefCreateAliasOut)(nil))))
}
