// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::TypeCode_id_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaTypeCodeIdOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaTypeCodeIdOutId_Const = "IDL:CORBA/TypeCode_id_Out:1.0"

func (self *CorbaTypeCodeIdOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaTypeCodeIdOut) GoString() string {
	return self.String()
}

func (self *CorbaTypeCodeIdOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaTypeCodeIdOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaTypeCodeIdOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaTypeCodeIdOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaTypeCodeIdOutHelper = CorbaTypeCodeIdOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaTypeCodeIdOutId_Const,
			__goidl__.StructType,
			"CORBA_TypeCode.idl",
			"xdl_CorbaTypeCodeIdOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaTypeCodeIdOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaTypeCodeIdOut{}
			},
			__reflect__.TypeOf((*CorbaTypeCodeIdOut)(nil))))
}
