// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::LocalInterfaceDef_destroy_In", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaLocalInterfaceDefDestroyIn struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaLocalInterfaceDefDestroyInId_Const = "IDL:CORBA/LocalInterfaceDef_destroy_In:1.0"

func (self *CorbaLocalInterfaceDefDestroyIn) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaLocalInterfaceDefDestroyIn) GoString() string {
	return self.String()
}

func (self *CorbaLocalInterfaceDefDestroyIn) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaLocalInterfaceDefDestroyIn) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaLocalInterfaceDefDestroyIn) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaLocalInterfaceDefDestroyIn_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaLocalInterfaceDefDestroyInHelper = CorbaLocalInterfaceDefDestroyIn_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaLocalInterfaceDefDestroyInId_Const,
			__goidl__.StructType,
			"CORBA_InterfaceRepository.idl",
			"xdl_CorbaLocalInterfaceDefDestroyIn.go",
			func() __goidl__.IIdlObject {
				return &CorbaLocalInterfaceDefDestroyIn{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaLocalInterfaceDefDestroyIn{}
			},
			__reflect__.TypeOf((*CorbaLocalInterfaceDefDestroyIn)(nil))))
}
