// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::Container_create_union_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaContainerCreateUnionOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaContainerCreateUnionOutId_Const = "IDL:CORBA/Container_create_union_Out:1.0"

func (self *CorbaContainerCreateUnionOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaContainerCreateUnionOut) GoString() string {
	return self.String()
}

func (self *CorbaContainerCreateUnionOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaContainerCreateUnionOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaContainerCreateUnionOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaContainerCreateUnionOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaContainerCreateUnionOutHelper = CorbaContainerCreateUnionOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaContainerCreateUnionOutId_Const,
			__goidl__.StructType,
			"CORBA_InterfaceRepository.idl",
			"xdl_CorbaContainerCreateUnionOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaContainerCreateUnionOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaContainerCreateUnionOut{}
			},
			__reflect__.TypeOf((*CorbaContainerCreateUnionOut)(nil))))
}
