// Code generated by me. DO NOT EDIT.

package goIdlCorba

import __goidl__ "github.com/bhbosman/goidl"
import __json__ "encoding/json"
import __reflect__ "reflect"

// Struct declaration: "CORBA::StructDef_lookup_Out", generatedBy by: "WriteStructDcl"
// Exception Decl: false
type CorbaStructDefLookupOut struct {
	__goidl__.IdlObject
}

//noinspection GoSnakeCaseUsage
const CorbaStructDefLookupOutId_Const = "IDL:CORBA/StructDef_lookup_Out:1.0"

func (self *CorbaStructDefLookupOut) String() string {
	b, err := __json__.Marshal(self)
	if err != nil {
		return ""
	}
	return string(b)
}

func (self *CorbaStructDefLookupOut) GoString() string {
	return self.String()
}

func (self *CorbaStructDefLookupOut) ReadValue(stream __goidl__.IReadAny) error {
	var err error
	err = self.IdlObject.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaStructDefLookupOut) Read(stream __goidl__.IReadAny) error {
	err := self.ReadValue(stream)
	if err != nil {
		return err
	}
	return nil
}

func (self *CorbaStructDefLookupOut) Write(stream __goidl__.IWriteAny) error {
	var err error
	err = self.IdlObject.Write(stream)
	if err != nil {
		return err
	}
	return nil
}

//noinspection GoSnakeCaseUsage
type CorbaStructDefLookupOut_Helper struct {
}


//noinspection GoUnusedGlobalVariable
var CorbaStructDefLookupOutHelper = CorbaStructDefLookupOut_Helper{}

func init() {
	__goidl__.AddRegistration(
		__goidl__.NewRegistrationInformation(
			CorbaStructDefLookupOutId_Const,
			__goidl__.StructType,
			"CORBA_InterfaceRepository.idl",
			"xdl_CorbaStructDefLookupOut.go",
			func() __goidl__.IIdlObject {
				return &CorbaStructDefLookupOut{}
			},
			func(generator __goidl__.IRandomDataGenerator) __goidl__.IIdlObject {
				return &CorbaStructDefLookupOut{}
			},
			__reflect__.TypeOf((*CorbaStructDefLookupOut)(nil))))
}
